language: cpp
compiler: gcc
sudo: false
dist: trusty

compiler:
  - gcc

addons:
  apt:
    packages: libboost1.58-dev

before_script:
  - grep "#define BOOST_VERSION " /usr/include/boost/version.hpp
  - uname -a
  - $CXX --version
  - cmake --version    

script:
  - mkdir -p build && cd build
  - cmake ..
  - make
  