language: cpp
sudo: false

os:
  - Linux
compiler:
  - gcc

addons:
  apt:
    packages:
      - libboost-all-dev
      - dpkg
      
install:
  # Freely inspired from https://github.com/boostorg/hana/blob/master/.travis.yml
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

script:
  - dpkg -s libboost-dev | grep 'Version'
  - uname -a
  - $CXX --version
  - cmake --version
  - mkdir -p build && cd build
  - cmake ..
  - make
  