language: cpp

dist: trusty
sudo: false
os: Linux
compiler: gcc

addons:
  apt:
    packages:
      - libboost-all-dev

script:
  - uname -a
  - $CXX --version
  - cmake --version
  - cat /usr/include/boost/version.hpp | grep "BOOST_LIB_VERSION"  
  - mkdir -p build && cd build
  - cmake ..
  - make
  