language: cpp

dist: trusty
sudo: false
os: Linux
compiler: gcc

addons:
  apt:
    packages:
      - libboost-all-dev

script:
  - uname -a
  - $CXX --version
  - cmake --version  
  - mkdir -p build && cd build
  - cmake ..
  - make
  